
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wempty-body"
#pragma GCC diagnostic ignored "-Wsign-compare"
#pragma GCC diagnostic ignored "-Wparentheses"

#if defined(M480)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/bpwm.c"
	#include "StdDriver/src/can.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/crc.c"
	#include "StdDriver/src/crypto.c"
	#include "StdDriver/src/dac.c"
	#include "StdDriver/src/eadc.c"
	#include "StdDriver/src/ebi.c"
	#include "StdDriver/src/ecap.c"
	#include "StdDriver/src/emac.c"
	#include "StdDriver/src/epwm.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/hsusbd.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/i2s.c"
	#include "StdDriver/src/pdma.c"
	#include "StdDriver/src/qei.c"
	#include "StdDriver/src/qspi.c"
	#include "StdDriver/src/rtc.c"
	#include "StdDriver/src/sc.c"
	#include "StdDriver/src/scuart.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/spim.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/timer_pwm.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/usbd.c"
	#include "StdDriver/src/usci_i2c.c"
	#include "StdDriver/src/usci_spi.c"
	#include "StdDriver/src/usci_uart.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"
#elif defined(M451Series)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/can.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/crc.c"
	#include "StdDriver/src/dac.c"
	#include "StdDriver/src/eadc.c"
	#include "StdDriver/src/ebi.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pdma.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/rtc.c"
	#include "StdDriver/src/sc.c"
	#include "StdDriver/src/scuart.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/tk.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/usbd.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"


#elif defined(NUC200Series)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/can.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/crc.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/i2s.c"
	#include "StdDriver/src/pdma.c"
	#include "StdDriver/src/ps2.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/rtc.c"
	#include "StdDriver/src/sc.c"
	#include "StdDriver/src/scuart.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/usbd.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"

#elif defined(NUC131)
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/bpwm.c"
	#include "StdDriver/src/can.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"

#elif defined(Nano100Series)
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/crc.c"
	#include "StdDriver/src/ebi.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/i2s.c"
	#include "StdDriver/src/lcd.c"
	#include "StdDriver/src/pdma.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/rtc.c"
	#include "StdDriver/src/sc.c"
	#include "StdDriver/src/scuart.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/usbd.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"

#elif defined(Nano1X2Series)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/crc.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/lcd.c"
	#include "StdDriver/src/pdma.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/rtc.c"
	#include "StdDriver/src/sc.c"
	#include "StdDriver/src/scuart.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"
	
#elif defined(M051Series)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/ebi.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pwm.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"
	
#elif defined(M058S)
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pwm.c"
//	#include "StdDriver/src/retarget.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"
	#include "StdDriver/src/wwdt.c"

#elif defined(Mini58Series)
	#include "StdDriver/src/acmp.c"
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pwm.c"
//	#include "StdDriver/src/retarget.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"

#elif defined(Mini51Series)
	#include "StdDriver/src/adc.c"
	#include "StdDriver/src/clk.c"
	#include "StdDriver/src/fmc.c"
	#include "StdDriver/src/gpio.c"
	#include "StdDriver/src/i2c.c"
	#include "StdDriver/src/pwm.c"
//	#include "StdDriver/src/retarget.c"
	#include "StdDriver/src/spi.c"
	#include "StdDriver/src/sys.c"
	#include "StdDriver/src/timer.c"
	#include "StdDriver/src/uart.c"
	#include "StdDriver/src/wdt.c"
	
#else
	#error "! the Series undef  or unsupport !"
#endif