/*
  Copyright (c) 2011 Arduino.  All right reserved.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include "Arduino.h"

#pragma GCC diagnostic ignored "-Wconversion-null"

#ifdef USE_BoardToPin
const BoardToPin BoardToPinInfo[] = 
 {{ 73, UART_TYPE, 0}, // 0: PC10(UART_RX0)
  { 72, UART_TYPE, 0}, // 1: PC11(UART_TX0)
  { 79, PWM_TYPE, 0}, // 2: PA12(PWM0)
  { 78, PWM_TYPE, 1}, // 3: PA13(PWM1)
  { 77, PWM_TYPE, 2}, // 4: PA14(PWM2)
  { 76, PWM_TYPE, 3}, // 5: PA15(PWM3)
  { 71, PWM_TYPE, 4}, // 6: PC12(PWM4)
  { 70, PWM_TYPE, 5}, // 7: PC13(PWM5)
  {109, PWM_TYPE, 6}, // 8: PC15(PWM6)
  {110, PWM_TYPE, 7}, // 9: PC14(PWM7)
  { 48, GPIO_TYPE, 0}, //10: PD6
  { 49, GPIO_TYPE, 0}, //11: PD7
  { 50, GPIO_TYPE, 0}, //12: PD14
  { 51, GPIO_TYPE, 0}, //13: PD15
  {  9, I2C_TYPE, 0}, //14: PA10(I2C1_SDA)
  { 10, I2C_TYPE, 0}, //15: PA11(I2C1_SCL)
  { 89, GPIO_TYPE, 0}, //16: PA0(ADC0)
  { 90, GPIO_TYPE, 0}, //17: PA1(ADC1)
  { 91, GPIO_TYPE, 0}, //18: PA2(ADC2)
  { 92, GPIO_TYPE, 0}, //19: PA3(ADC3)
  { 93, GPIO_TYPE, 0}, //20: PA4(ADC4)
  { 94, GPIO_TYPE, 0}, //21: PA5(ADC5)
  { 95, GPIO_TYPE, 0}, //22: PA6(ADC6)
  { 96, GPIO_TYPE, 0}, //23: PA7(ADC7)
  {100, GPIO_TYPE, 0}, //24: PD0(ADC8)
  {101, GPIO_TYPE, 0}, //25: PD1(ADC9)
  { 13, GPIO_TYPE, 0}, //26: PD8
  { 14, GPIO_TYPE, 0}, //27: PD9
  {108, GPIO_TYPE, 0}, //28: PC6
  {107, GPIO_TYPE, 0}, //29: PC7
  { 15, GPIO_TYPE, 0}, //30: PD10
  { 16, GPIO_TYPE, 0}, //31: PD11
  { 11, I2C_TYPE, 1}, //32: PA9(I2C0_SCL)
  { 12, I2C_TYPE, 1}, //33: PA8(I2C0_SDA)
  { 44, UART_TYPE, 1}, //34: PB0(UART_RX1)
  { 45, UART_TYPE, 1}, //35: PB1(UART_TX1)
  { 36, GPIO_TYPE, 0}, //36: PE9
  { 35, GPIO_TYPE, 0}, //37: PE10
  { 34, GPIO_TYPE, 0}, //38: PE11
  { 33, GPIO_TYPE, 0}, //39: PE12
  { 66, SPI_TYPE, 0}, //40: PE3(SPI0_MISO0)
  { 67, SPI_TYPE, 0}, //41: PE2(SPI0_SCLK)
  { 65, SPI_TYPE, 0}, //42: PE4(SPI0_MOSI0)
  { 68, SPI_TYPE, 0}, //43: PE1(SPI0_SS0)
  { 17, GPIO_TYPE, 0}, //44: PD12
  {127, GPIO_TYPE, 0}, //45: PE15
  {  4, GPIO_TYPE, 0}, //46: PB12(CKO)
  {122, GPIO_TYPE, 0}, //47: PF4
  { 69, GPIO_TYPE, 0}, //48: PE0(I2S_MCLK)
  {123, GPIO_TYPE, 0}, //49: PF5
  {102, GPIO_TYPE, 0}, //50: PD2(I2S_LRCK)
  { 75, GPIO_TYPE, 0}, //51: PC8
  {103, GPIO_TYPE, 0}, //52: PD3(I2S_BCLK)
  { 74, GPIO_TYPE, 0}, //53: PC9
  {105, GPIO_TYPE, 0}, //54: PD4(I2S_DI)
  { 53, GPIO_TYPE, 0}, //55: PC4
  {106, GPIO_TYPE, 0}, //56: PD5(I2S_DO)
  { 52, GPIO_TYPE, 0}, //57: PC5
  { 76, GPIO_TYPE, 0}, //58: PA15(TMR0_CAP)
  { 55, GPIO_TYPE, 0}, //59: PC2(SC0_POR)
  { 64, GPIO_TYPE, 0}, //60: PB9(TMR0_OUT)
  { 54, GPIO_TYPE, 0}, //61: PC3(SC0_RST)
  { 63, GPIO_TYPE, 0}, //62: PB10
  { 57, GPIO_TYPE, 0}, //63: PC0(SC0_CLK)
  { 62, GPIO_TYPE, 0}, //64: PB11
  { 56, GPIO_TYPE, 0}, //65: PC1(SC0_DAT)
  { 61, GPIO_TYPE, 0}, //66: PE5
  {111, GPIO_TYPE, 0}, //67: PB15(SC0_CS)
  { 19, GPIO_TYPE, 0}, //68: PB4
  { 47, GPIO_TYPE, 0}, //69: PB3(UART1_CTS)
  { 20, GPIO_TYPE, 0}, //70: PB5
  { 46, GPIO_TYPE, 0}, //71: PB2(UART1_RTS)
  { 21, GPIO_TYPE, 0}, //72: PB6
  { 38, GPIO_TYPE, 0}, //73: PE7
  { 22, GPIO_TYPE, 0}, //74: PB7
  { 37, GPIO_TYPE, 0}, //75: PE8
  { 58, GPIO_TYPE, 0}, //76: PE6
  {  2, GPIO_TYPE, 0}, //77: PB14(EINT0)
  { 18, GPIO_TYPE, 0}, //78: PD13
  {  1, GPIO_TYPE, 0}, //79: PE13
  {  3, GPIO_TYPE, 0}, //80: PB13
};
#endif


const GPIOPinDescription GPIO_Desc[] =
{
  {NULL, NULL, {NULL, NULL, NULL}}, //0
  {PE, BIT13, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE13_MFP_Msk, SYS_PE_H_MFP_PE13_MFP_GPE13}}, //1
  {PB, BIT14, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB14_MFP_Msk, SYS_PB_H_MFP_PB14_MFP_GPB14}}, //2
  {PB, BIT13, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB13_MFP_Msk, SYS_PB_H_MFP_PB13_MFP_GPB13}}, //3
  {PB, BIT12, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB12_MFP_Msk, SYS_PB_H_MFP_PB12_MFP_GPB12}}, //4
  {NULL, NULL, {NULL, NULL, NULL}}, /* 5,NC                                        */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 6,X32_OUT                                   */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 7,X32_IN                                    */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 8,NC                                        */
  {PA, BIT11, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA11_MFP_Msk, SYS_PA_H_MFP_PA11_MFP_GPA11}}, //9
  {PA, BIT10, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA10_MFP_Msk, SYS_PA_H_MFP_PA10_MFP_GPA10}}, //10
  {PA, BIT9, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA9_MFP_Msk,   SYS_PA_H_MFP_PA9_MFP_GPA9}},   //11
  {PA, BIT8, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA8_MFP_Msk,   SYS_PA_H_MFP_PA8_MFP_GPA8}},   //12
  {PD, BIT8, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD8_MFP_Msk,   SYS_PD_H_MFP_PD8_MFP_GPD8}},   //13
  {PD, BIT9, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD9_MFP_Msk,   SYS_PD_H_MFP_PD9_MFP_GPD9}},   //14
  {PD, BIT10, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD10_MFP_Msk, SYS_PD_H_MFP_PD10_MFP_GPD10}}, //15
  {PD, BIT11, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD11_MFP_Msk, SYS_PD_H_MFP_PD11_MFP_GPD11}}, //16
  {PD, BIT12, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD12_MFP_Msk, SYS_PD_H_MFP_PD12_MFP_GPD12}}, //17
  {PD, BIT13, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD13_MFP_Msk, SYS_PD_H_MFP_PD13_MFP_GPD13}}, //18
  {PB, BIT4, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB4_MFP_Msk, SYS_PB_L_MFP_PB4_MFP_GPB4}},   //19
  {PB, BIT5, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB5_MFP_Msk, SYS_PB_L_MFP_PB5_MFP_GPB5}},   //20
  {PB, BIT6, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB6_MFP_Msk, SYS_PB_L_MFP_PB6_MFP_GPB6}},   //21
  {PB, BIT7, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB7_MFP_Msk, SYS_PB_L_MFP_PB7_MFP_GPB7}},   //22
  {NULL, NULL, {NULL, NULL, NULL}}, /* 23,NC      */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 24,LDO_CAP */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 25,NC      */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 26,NC      */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 27,VDD     */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 28,NC      */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 29,VSS     */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 30,VSS     */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 31,VSS     */
  {NULL, NULL, {NULL, NULL, NULL}}, /* 32,VSS     */
  {PE, BIT12, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE12_MFP_Msk, SYS_PE_H_MFP_PE12_MFP_GPE12}}, //33
  {PE, BIT11, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE11_MFP_Msk, SYS_PE_H_MFP_PE11_MFP_GPE11}}, //34
  {PE, BIT10, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE10_MFP_Msk, SYS_PE_H_MFP_PE10_MFP_GPE10}}, //35
  {PE, BIT9, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE9_MFP_Msk,   SYS_PE_H_MFP_PE9_MFP_GPE9}},   //36
  {PE, BIT8, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE8_MFP_Msk,   SYS_PE_H_MFP_PE8_MFP_GPE8}},   //37
  {PE, BIT7, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE7_MFP_Msk,   SYS_PE_L_MFP_PE7_MFP_GPE7}},   //38
  {NULL, NULL, {NULL, NULL, NULL}}, /*39,NC             */          
  {NULL, NULL, {NULL, NULL, NULL}}, /*40,USB_VBUS       */
  {NULL, NULL, {NULL, NULL, NULL}}, /*41,USB_VDD33_CAP  */
  {NULL, NULL, {NULL, NULL, NULL}}, /*42,USB_D-         */
  {NULL, NULL, {NULL, NULL, NULL}}, /*43,USB_D+         */
  {PB, BIT0, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB0_MFP_Msk, SYS_PB_L_MFP_PB0_MFP_GPB0}},   //44
  {PB, BIT1, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB1_MFP_Msk, SYS_PB_L_MFP_PB1_MFP_GPB1}},   //45
  {PB, BIT2, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB2_MFP_Msk, SYS_PB_L_MFP_PB2_MFP_GPB2}},   //46
  {PB, BIT3, {(uint32_t)&SYS->PB_L_MFP, SYS_PB_L_MFP_PB3_MFP_Msk, SYS_PB_L_MFP_PB3_MFP_GPB3}},   //47
  {PD, BIT6, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD6_MFP_Msk, SYS_PD_L_MFP_PD6_MFP_GPD6}},   //48
  {PD, BIT7, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD7_MFP_Msk, SYS_PD_L_MFP_PD7_MFP_GPD7}},   //49
  {PD, BIT14, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD14_MFP_Msk, SYS_PD_H_MFP_PD14_MFP_GPD14}}, //50
  {PD, BIT15, {(uint32_t)&SYS->PD_H_MFP, SYS_PD_H_MFP_PD15_MFP_Msk, SYS_PD_H_MFP_PD15_MFP_GPD15}}, //51
  {PC, BIT5, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC5_MFP_Msk, SYS_PC_L_MFP_PC5_MFP_GPC5}},   //52
  {PC, BIT4, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC4_MFP_Msk, SYS_PC_L_MFP_PC4_MFP_GPC4}},   //53
  {PC, BIT3, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC3_MFP_Msk, SYS_PC_L_MFP_PC3_MFP_GPC3}},   //54
  {PC, BIT2, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC2_MFP_Msk, SYS_PC_L_MFP_PC2_MFP_GPC2}},   //55
  {PC, BIT1, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC1_MFP_Msk, SYS_PC_L_MFP_PC1_MFP_GPC1}},   //56
  {PC, BIT0, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC0_MFP_Msk, SYS_PC_L_MFP_PC0_MFP_GPC0}},   //57
  {PE, BIT6, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE6_MFP_Msk, SYS_PE_L_MFP_PE6_MFP_GPE6}},   //58
  {NULL, NULL, {NULL, NULL, NULL}}, /*59,LCD_VLCD */
  {NULL, NULL, {NULL, NULL, NULL}}, /*60,NC       */
  {PE, BIT5, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE5_MFP_Msk, SYS_PE_L_MFP_PE5_MFP_GPE5}},   //61
  {PB, BIT11, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB11_MFP_Msk, SYS_PB_H_MFP_PB11_MFP_GPB11}}, //62
  {PB, BIT10, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB10_MFP_Msk, SYS_PB_H_MFP_PB10_MFP_GPB10}}, //63
  {PB, BIT9, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB9_MFP_Msk, SYS_PB_H_MFP_PB9_MFP_GPB9}},   //64
  {PE, BIT4, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE4_MFP_Msk, SYS_PE_L_MFP_PE4_MFP_GPE4}},   //65
  {PE, BIT3, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE3_MFP_Msk, SYS_PE_L_MFP_PE3_MFP_GPE3}},   //66
  {PE, BIT2, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE2_MFP_Msk, SYS_PE_L_MFP_PE2_MFP_GPE2}},   //67
  {PE, BIT1, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE1_MFP_Msk, SYS_PE_L_MFP_PE1_MFP_GPE1}},   //68
  {PE, BIT0, {(uint32_t)&SYS->PE_L_MFP, SYS_PE_L_MFP_PE0_MFP_Msk, SYS_PE_L_MFP_PE0_MFP_GPE0}},   //69
  {PC, BIT13, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC13_MFP_Msk, SYS_PC_H_MFP_PC13_MFP_GPC13}}, //70
  {PC, BIT12, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC12_MFP_Msk, SYS_PC_H_MFP_PC12_MFP_GPC12}}, //71
  {PC, BIT11, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC11_MFP_Msk, SYS_PC_H_MFP_PC11_MFP_GPC11}}, //72
  {PC, BIT10, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC10_MFP_Msk, SYS_PC_H_MFP_PC10_MFP_GPC10}}, //73
  {PC, BIT9, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC9_MFP_Msk, SYS_PC_H_MFP_PC9_MFP_GPC9 }},   //74
  {PC, BIT8, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC8_MFP_Msk, SYS_PC_H_MFP_PC8_MFP_GPC8 }},   //75
  {PA, BIT15, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA15_MFP_Msk, SYS_PA_H_MFP_PA15_MFP_GPA15}}, //76
  {PA, BIT14, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA14_MFP_Msk, SYS_PA_H_MFP_PA14_MFP_GPA14}}, //77
  {PA, BIT13, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA13_MFP_Msk, SYS_PA_H_MFP_PA13_MFP_GPA13}}, //78
  {PA, BIT12, {(uint32_t)&SYS->PA_H_MFP, SYS_PA_H_MFP_PA12_MFP_Msk, SYS_PA_H_MFP_PA12_MFP_GPA12}}, //79
  {PF, BIT0, {(uint32_t)&SYS->PF_L_MFP, SYS_PF_L_MFP_PF0_MFP_Msk, SYS_PF_L_MFP_PF0_MFP_GPF0}},   //80
  {PF, BIT1, {(uint32_t)&SYS->PF_L_MFP, SYS_PF_L_MFP_PF1_MFP_Msk, SYS_PF_L_MFP_PF1_MFP_GPF1}},   //81
  {NULL, NULL, {NULL, NULL, NULL}}, /*82,NC  */
  {NULL, NULL, {NULL, NULL, NULL}}, /*83,VDD */
  {NULL, NULL, {NULL, NULL, NULL}}, /*84,NC  */
  {NULL, NULL, {NULL, NULL, NULL}}, /*85,VSS */
  {NULL, NULL, {NULL, NULL, NULL}}, /*86,VSS */
  {NULL, NULL, {NULL, NULL, NULL}}, /*87,AVSS*/
  {NULL, NULL, {NULL, NULL, NULL}}, /*88,AVSS*/
  {PA, BIT0, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA0_MFP_Msk, SYS_PA_L_MFP_PA0_MFP_GPA0}}, //89
  {PA, BIT1, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA1_MFP_Msk, SYS_PA_L_MFP_PA1_MFP_GPA1}}, //90
  {PA, BIT2, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA2_MFP_Msk, SYS_PA_L_MFP_PA2_MFP_GPA2}}, //91
  {PA, BIT3, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA3_MFP_Msk, SYS_PA_L_MFP_PA3_MFP_GPA3}}, //92
  {PA, BIT4, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA4_MFP_Msk, SYS_PA_L_MFP_PA4_MFP_GPA4}}, //93
  {PA, BIT5, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA5_MFP_Msk, SYS_PA_L_MFP_PA5_MFP_GPA5}}, //94
  {PA, BIT6, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA6_MFP_Msk, SYS_PA_L_MFP_PA6_MFP_GPA6}}, //95
  {PA, BIT7, {(uint32_t)&SYS->PA_L_MFP, SYS_PA_L_MFP_PA7_MFP_Msk, SYS_PA_L_MFP_PA7_MFP_GPA7}}, //96
  {NULL, NULL, {NULL, NULL, NULL}}, /*97,VREF*/
  {NULL, NULL, {NULL, NULL, NULL}}, /*98,NC  */
  {NULL, NULL, {NULL, NULL, NULL}}, /*99,AVDD*/
  {PD, BIT0, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD0_MFP_Msk, SYS_PD_L_MFP_PD0_MFP_GPD0 }},   //100
  {PD, BIT1, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD1_MFP_Msk, SYS_PD_L_MFP_PD1_MFP_GPD1 }},   //101
  {PD, BIT2, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD2_MFP_Msk, SYS_PD_L_MFP_PD2_MFP_GPD2 }},   //102
  {PD, BIT3, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD3_MFP_Msk, SYS_PD_L_MFP_PD3_MFP_GPD3 }},   //103
  {PD, BIT4, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD4_MFP_Msk, SYS_PD_L_MFP_PD4_MFP_GPD4 }},   //105
  {PD, BIT5, {(uint32_t)&SYS->PD_L_MFP, SYS_PD_L_MFP_PD5_MFP_Msk, SYS_PD_L_MFP_PD5_MFP_GPD5 }},   //106
  {PC, BIT7, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC7_MFP_Msk, SYS_PC_L_MFP_PC7_MFP_GPC7 }},   //107
  {PC, BIT6, {(uint32_t)&SYS->PC_L_MFP, SYS_PC_L_MFP_PC6_MFP_Msk, SYS_PC_L_MFP_PC6_MFP_GPC6 }},   //108
  {PC, BIT15, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC15_MFP_Msk, SYS_PC_H_MFP_PC15_MFP_GPC15}}, //109
  {PC, BIT14, {(uint32_t)&SYS->PC_H_MFP, SYS_PC_H_MFP_PC14_MFP_Msk, SYS_PC_H_MFP_PC14_MFP_GPC14}}, //110
  {PB, BIT15, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB15_MFP_Msk, SYS_PB_H_MFP_PB15_MFP_GPB15}}, //111
  {NULL, NULL, {NULL, NULL, NULL}}, /*112,NC     */
  {NULL, NULL, {NULL, NULL, NULL}}, /*113,XT1_IN */
  {NULL, NULL, {NULL, NULL, NULL}}, /*114,XT1_OUT*/
  {NULL, NULL, {NULL, NULL, NULL}}, /*115,NC     */
  {NULL, NULL, {NULL, NULL, NULL}}, /*116,nRESET */
  {NULL, NULL, {NULL, NULL, NULL}}, /*117,VSS    */
  {NULL, NULL, {NULL, NULL, NULL}}, /*118,VSS    */
  {NULL, NULL, {NULL, NULL, NULL}}, /*119,NC     */
  {NULL, NULL, {NULL, NULL, NULL}}, /*120,VDD    */
  {NULL, NULL, {NULL, NULL, NULL}}, /*121,NC     */
  {PF, BIT4, {(uint32_t)&SYS->PF_L_MFP, SYS_PF_L_MFP_PF4_MFP_Msk, SYS_PF_L_MFP_PF4_MFP_GPF4 }}, //122
  {PF, BIT5, {(uint32_t)&SYS->PF_L_MFP, SYS_PF_L_MFP_PF5_MFP_Msk, SYS_PF_L_MFP_PF5_MFP_GPF5 }}, //123
  {NULL, NULL, {NULL, NULL, NULL}}, /*124,VSS */
  {NULL, NULL, {NULL, NULL, NULL}}, /*125,PVSS*/
  {PB, BIT8, {(uint32_t)&SYS->PB_H_MFP, SYS_PB_H_MFP_PB8_MFP_Msk, SYS_PB_H_MFP_PB8_MFP_GPB8 }},   //126
  {PE, BIT15, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE15_MFP_Msk, SYS_PE_H_MFP_PE15_MFP_GPE15}}, //127
  {PE, BIT14, {(uint32_t)&SYS->PE_H_MFP, SYS_PE_H_MFP_PE14_MFP_Msk, SYS_PE_H_MFP_PE14_MFP_GPE14}}, //128

};

const PWMPinDescription PWM_Desc[] = {
  {PWM0, PWM0_CH01_MODULE, PWM0_IRQn, 0, 500, {PA_12, SYS_PA_H_MFP_PA12_MFP_PWM0_CH0}}, //0
  {PWM0, PWM0_CH01_MODULE, PWM0_IRQn, 1, 500, {PA_13, SYS_PA_H_MFP_PA13_MFP_PWM0_CH1}}, //1
  {PWM0, PWM0_CH23_MODULE, PWM0_IRQn, 2, 500, {PA_14, SYS_PA_H_MFP_PA14_MFP_PWM0_CH2}}, //2
  {PWM0, PWM0_CH23_MODULE, PWM0_IRQn, 3, 500, {PA_15, SYS_PA_H_MFP_PA15_MFP_PWM0_CH3}}, //3
  {PWM1, PWM1_CH01_MODULE, PWM1_IRQn, 0, 500, {PC_12, SYS_PC_H_MFP_PC12_MFP_PWM1_CH0}}, //4
  {PWM1, PWM1_CH01_MODULE, PWM1_IRQn, 1, 500, {PC_13, SYS_PC_H_MFP_PC13_MFP_PWM1_CH1}}, //5
  {PWM1, PWM1_CH23_MODULE, PWM1_IRQn, 2, 500, {PC_15, SYS_PC_H_MFP_PC15_MFP_PWM1_CH2}}, //6
  {PWM1, PWM1_CH23_MODULE, PWM1_IRQn, 3, 500, {PC_14, SYS_PC_H_MFP_PC14_MFP_PWM1_CH3}}, //7
};

const ADCPinDescription ADC_Desc[] = {
  {ADC, ADC_MODULE, 0, {PA_0, SYS_PA_L_MFP_PA0_MFP_ADC_CH0}}, //0
  {ADC, ADC_MODULE, 1, {PA_1, SYS_PA_L_MFP_PA1_MFP_ADC_CH1}}, //1
  {ADC, ADC_MODULE, 2, {PA_2, SYS_PA_L_MFP_PA2_MFP_ADC_CH2}}, //2
  {ADC, ADC_MODULE, 3, {PA_3, SYS_PA_L_MFP_PA3_MFP_ADC_CH3}}, //3
  {ADC, ADC_MODULE, 4, {PA_4, SYS_PA_L_MFP_PA4_MFP_ADC_CH4}}, //4
  {ADC, ADC_MODULE, 5, {PA_5, SYS_PA_L_MFP_PA5_MFP_ADC_CH5}}, //5
  {ADC, ADC_MODULE, 6, {PA_6, SYS_PA_L_MFP_PA6_MFP_ADC_CH6}}, //6
  {ADC, ADC_MODULE, 7, {PA_7, SYS_PA_L_MFP_PA7_MFP_ADC_CH7}}, //7
  {ADC, ADC_MODULE, 8, {PD_0, SYS_PD_L_MFP_PD0_MFP_ADC_CH8}}, //8
  {ADC, ADC_MODULE, 9, {PD_1, SYS_PD_L_MFP_PD1_MFP_ADC_CH9}}, //9
};


const SPIPinDescription SPI_Desc[] = {
  { SPI0, SPI0_MODULE, SPI0_IRQn, CLK_CLKSEL2_SPI0_S_HCLK,
    { {PE_2, SYS_PE_L_MFP_PE2_MFP_SPI0_SCLK  }, {PE_4, SYS_PE_L_MFP_PE4_MFP_SPI0_MOSI0 },
      {PE_3, SYS_PE_L_MFP_PE3_MFP_SPI0_MISO0 }, {PE_1, SYS_PE_L_MFP_PE1_MFP_SPI0_SS0}
    }
  },

  { SPI1, SPI1_MODULE, SPI1_IRQn, CLK_CLKSEL2_SPI1_S_HCLK,
    { {PB_2, SYS_PB_L_MFP_PB2_MFP_SPI1_SCLK  }, {PB_0, SYS_PB_L_MFP_PB0_MFP_SPI1_MOSI0 },
      {PB_1, SYS_PB_L_MFP_PB1_MFP_SPI1_MISO0 }, {PB_3, SYS_PB_L_MFP_PB3_MFP_SPI1_SS0}
    }
  },

  { SPI2, SPI2_MODULE, SPI2_IRQn, CLK_CLKSEL2_SPI2_S_HCLK,
    { {PB_5, SYS_PB_L_MFP_PB5_MFP_SPI2_SCLK  }, {PB_7, SYS_PB_L_MFP_PB7_MFP_SPI2_MOSI0 },
      {PB_6, SYS_PB_L_MFP_PB6_MFP_SPI2_MISO0 }, {PB_4, SYS_PB_L_MFP_PB4_MFP_SPI2_SS0}
    }
  },
};

const UARTPinDescription UART_Desc[] = {
  {UART1, UART1_MODULE, UART1_IRQn, {{PC_10, SYS_PC_H_MFP_PC10_MFP_UART1_RX}, {PC_11, SYS_PC_H_MFP_PC11_MFP_UART1_TX}}}, /* UART_RX0,UART_TX0 */
  {UART0, UART0_MODULE, UART0_IRQn, { {PB_0, SYS_PB_L_MFP_PB0_MFP_UART0_RX }, {PB_1,   SYS_PB_L_MFP_PB1_MFP_UART0_TX}}},  /* UART_RX1,UART_TX1 */
};

const I2CPinDescription I2C_Desc[] = {
  {I2C1, I2C1_MODULE, {{PA_11, SYS_PA_H_MFP_PA11_MFP_I2C1_SCL}, {PA_10, SYS_PA_H_MFP_PA10_MFP_I2C1_SDA}}}, /* I2C0_SDA,I2C0_SCL */
  {I2C0, I2C0_MODULE, {{PA_9,  SYS_PA_H_MFP_PA9_MFP_I2C0_SCL },  {PA_8, SYS_PA_H_MFP_PA8_MFP_I2C0_SDA }}},   /* I2C1_SDA,I2C1_SCL */
};
